#
# scss lint setting yml
# @see https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md
#

linters:
  # border: 0 -> border: none
  BorderZero:
    convention: none

  # color: white などの利用を禁止
  ColorKeyword:
    enabled: false

  # color: $body-color のように変数を強制する
  ColorVariable:
    enabled: false

  # /* */ でのコメントを禁止
  Comment:
    enabled: false

  # @extend, @include, @content の記述順をスコープの先頭に強制する
  DeclarationOrder:
    enabled: false

  # プロパティの重複
  # ブラウザ対応等の為に連続 (同じ値を別の表現で設定) させている場合は無視する (別の値を設定するのはNG) (default: false)
  DuplicateProperty:
    ignore_consecutive: true

  # ルール間に改行を強制する
  EmptyLineBetweenBlocks:
    enabled: true
    severity: error

  # !importantを禁止
  ImportantRule:
    enabled: false

  # Reports when you define the same selector twice in a single sheet
  MergeableSelector:
    force_nesting: false

  # ネストの深さを制限する (default: 3)
  NestingDepth:
    max_depth: 9

  # Always use placeholder selectors in @extend.
  PlaceholderInExtend:
    enabled: false

  # プロパティの記述順を強制する
  PropertySortOrder:
    enabled: false

  # div.selector などの書き方を制限する
  QualifyingElement:
    allow_element_with_attribute: true
    allow_element_with_class: true

  # セレクタの深さを制限する (default: 3)
  SelectorDepth:
    enabled: false
